version: '3'
services:
  products-frontend-local:
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development